# Generated by Django 5.0.7 on 2026-08-10 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholarships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('degree_field', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('has_ielts', models.BooleanField(default=False)),
                ('ielts_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('has_toefl', models.BooleanField(default=False)),
                ('toefl_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('not_started', 'Not Started'), ('not_needed', 'Not Needed')], default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tracker.applicantprofile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrackedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('researching', 'Researching'), ('planning', 'Planning'), ('drafting', 'Drafting'), ('submitted', 'Submitted'), ('interview', 'Interview'), ('awarded', 'Awarded'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='researching', max_length=30)),
                ('priority', models.CharField(choices=[('reach', 'Reach'), ('target', 'Target'), ('safe', 'Safe'), ('backup', 'Backup')], default='target', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('next_action_due', models.DateField(blank=True, null=True)),
                ('sop_status', models.CharField(choices=[('not_started', 'Not Started'), ('drafting', 'Drafting'), ('done', 'Done')], default='not_started', max_length=20)),
                ('refs_status', models.CharField(choices=[('not_started', 'Not Started'), ('requested', 'Requested'), ('received', 'Received')], default='not_started', max_length=20)),
                ('transcript_ready', models.BooleanField(default=False)),
                ('moi_ready', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tracker.applicantprofile')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by', to='scholarships.scholarship')),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('profile', 'scholarship')},
            },
        ),
    ]
