# Generated by Django 5.0.7 on 2026-08-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(max_length=2, unique=True, verbose_name='ISO code')),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(choices=[('Europe', 'Europe'), ('Asia', 'Asia'), ('Africa', 'Africa'), ('Americas', 'Americas'), ('Oceania', 'Oceania'), ('Multi', 'Multi-country')], default='Europe', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon, e.g. 🌱', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'fields of study',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('programme', models.CharField(blank=True, max_length=300)),
                ('university', models.CharField(blank=True, max_length=300)),
                ('funding_type', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('tuition_only', 'Tuition Only'), ('living_only', 'Living Only')], max_length=20)),
                ('funding_detail', models.TextField(blank=True)),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('eligibility_label', models.CharField(choices=[('CE', 'Confirmed Eligible'), ('LE', 'Likely Eligible'), ('PE', 'Pending Clarification'), ('NE', 'Not Eligible')], default='PE', max_length=2)),
                ('english_requirement', models.TextField(blank=True)),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experience_years_min', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('gpa_minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nationality_notes', models.TextField(blank=True)),
                ('mba_impact', models.CharField(choices=[('none', 'No impact'), ('risk', 'Risk'), ('disqualifies', 'Disqualifies'), ('check', 'Check'), ('unknown', 'Unknown')], default='none', max_length=20)),
                ('mba_notes', models.TextField(blank=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('competitiveness', models.CharField(blank=True, max_length=50)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('deadline_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open_now', 'Open Now'), ('opening_soon', 'Opening Soon'), ('upcoming', 'Upcoming'), ('not_yet_open', 'Not Yet Open'), ('closed', 'Closed'), ('ineligible', 'Ineligible'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('cycle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('action_required', models.TextField(blank=True)),
                ('official_link', models.URLField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_source', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarships', to='scholarships.country')),
                ('fields', models.ManyToManyField(blank=True, related_name='scholarships', to='scholarships.fieldofstudy')),
            ],
            options={
                'ordering': ['-score', 'deadline_date'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(default='update', max_length=50)),
                ('field_changed', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(default='system', max_length=100)),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='scholarships.scholarship')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['country'], name='scholarship_country_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['status'], name='scholarship_status_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['-score'], name='scholarship_score_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['deadline_date'], name='scholarship_deadline_idx'),
        ),
    ]
